### ISSUE TITLE
Stop button should be enabled when search starts

### ISSUE THREAD

**Issue by nadia-polikarpova** [davidmrdavid/hoogle_plus#129]
Right now the "Stop" button only gets enabled after the first result appears. This is annoying if I made a mistake in the query, now I need to wait forever for the search to fail.

**Comment by aaronguo1996** [comment]
This cannot be implemented right now because we cannot get the process id at the back end until we get the first solution. But there are two options here:
1. we have a special protocol that before sending back solutions, I will first send back the queryId alone so that we are able to kill that process before solution come
2. we fake a stop action when the queryId is null by saying we reset the search state on front end but leave that process executing at the back end

@michaelbjames what do you think?

**Comment by michaelbjames** [comment]
I can change the FE to drop the request when you click the stop button if we haven't heard anything back yet. This might even trigger some kind of exception you could catch in python.

So, yes this can be done, with varying degrees of being polite to the backing server.
