### ISSUE TITLE
Arg count not reset after type query changed

### ISSUE THREAD

**Issue by aaronguo1996** [davidmrdavid/hoogle_plus#143]
Steps to reproduce:
- Search by type `Eq a => [a] -> [a]` with example `[1,1,1,2,2,2,1,1,1] => [1,2,1]`
- Stop the search without clear the examples
- Reenter type query `(a -> a) -> Int -> a -> a`

The argument count didn't change.

**Comment by michaelbjames** [comment]
Yup, this is expected behavior. You shouldn't be able to hit "search" though. The thinking is that if you put in an example first and start to put in a type, the site shouldn't delete your examples.

I could imagine that we add/remove blank arguments, if there are more argument slots than we have inputs in the examples.

What do you think?

**Comment by aaronguo1996** [comment]
Okay, that's fair.
